[package]
name = "rustlr"
version = "0.1.0"
authors = ["Chuck Liang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
