[package]
name = "lambda7c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustlr = { path = "../../../rustlr" }
fixedstr = "0.2.8"
bumpalo = "3"
