[package]
name = "jsontypes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustlr = { path = "../../../rustlr", default-features=false }
#num = "0.4.0"
#impls = "1"
