[package]
name = "lambdascript"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#basic_lexer = "0.1.3"
rustlr = "0.2"
#{ path = "../../../rustlr" }
fixedstr = "0.1.2"
chrono = "0.4"
